name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Wichtig: Gibt die Berechtigung zum Erstellen von Releases

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -r win-x64 -c Release --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DesktopUhr
        path: bin/Release/net9.0-windows/win-x64/publish/DesktopUhr.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: DesktopUhr

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: DesktopUhr.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}
